name: power-market-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=1.5.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - plotly>=5.17.0
  - jupyterlab>=4.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - statsmodels>=0.14.0
  - ipywidgets>=8.0.0
  - openpyxl>=3.1.0
  - beautifulsoup4>=4.12.0
  - lxml>=4.9.0
  - requests>=2.28.0
  - dash=3.1.1
  - networkx=3.5
  - pytz>=2023.3
  - jupyter-console>=6.6.0
  - ipykernel>=6.25.0
  - pip
  - pip:
    - entsoe-py>=0.5.0
    - holidays>=0.34
